table FactLead
	lineageTag: aaaaaaaa-0000-0000-0000-000000000021

	measure 'Total Leads' = COUNTROWS('FactLead')
		formatString: 0
		lineageTag: aaaaaaaa-0000-0000-0000-000000000022

	measure 'Won Leads' = CALCULATE(COUNTROWS('FactLead'), 'FactLead'[IsWon] = 1)
		formatString: 0
		lineageTag: aaaaaaaa-0000-0000-0000-000000000023

	measure 'Lost Leads' = CALCULATE(COUNTROWS('FactLead'), 'FactLead'[IsLost] = 1)
		formatString: 0
		lineageTag: aaaaaaaa-0000-0000-0000-000000000024

	measure 'Win Rate' = DIVIDE([Won Leads], [Won Leads] + [Lost Leads])
		formatString: 0.0%
		lineageTag: aaaaaaaa-0000-0000-0000-000000000025

	measure 'Pipeline Value' = CALCULATE(SUM('FactLead'[EstimatedValue]), 'FactLead'[IsOpen] = 1)
		formatString: \$#,0
		lineageTag: aaaaaaaa-0000-0000-0000-000000000026

	measure 'Won Value' = CALCULATE(SUM('FactLead'[EstimatedValue]), 'FactLead'[IsWon] = 1)
		formatString: \$#,0
		lineageTag: aaaaaaaa-0000-0000-0000-000000000027

	column LeadKey
		dataType: int64
		summarizeBy: none
		sourceColumn: LeadKey
		lineageTag: aaaaaaaa-0000-0000-0000-000000000028

	column CustomerName
		dataType: string
		summarizeBy: none
		sourceColumn: CustomerName
		lineageTag: aaaaaaaa-0000-0000-0000-000000000029

	column RepKey
		dataType: int64
		summarizeBy: none
		sourceColumn: RepKey
		lineageTag: aaaaaaaa-0000-0000-0000-000000000030

	column LeadSourceKey
		dataType: int64
		summarizeBy: none
		sourceColumn: LeadSourceKey
		lineageTag: aaaaaaaa-0000-0000-0000-000000000031

	column CurrentStageKey
		dataType: int64
		summarizeBy: none
		sourceColumn: CurrentStageKey
		lineageTag: aaaaaaaa-0000-0000-0000-000000000032

	column CreatedDateKey
		dataType: int64
		summarizeBy: none
		sourceColumn: CreatedDateKey
		lineageTag: aaaaaaaa-0000-0000-0000-000000000033

	column EstimatedValue
		dataType: double
		summarizeBy: sum
		sourceColumn: EstimatedValue
		lineageTag: aaaaaaaa-0000-0000-0000-000000000034

	column IsWon
		dataType: int64
		summarizeBy: none
		sourceColumn: IsWon
		lineageTag: aaaaaaaa-0000-0000-0000-000000000035

	column IsLost
		dataType: int64
		summarizeBy: none
		sourceColumn: IsLost
		lineageTag: aaaaaaaa-0000-0000-0000-000000000036

	column IsOpen
		dataType: int64
		summarizeBy: none
		sourceColumn: IsOpen
		lineageTag: aaaaaaaa-0000-0000-0000-000000000037

	partition FactLead = entity
		mode: directLake
		source
			entityName: FactLead
			schemaName: dbo
			expressionSource: DatabaseQuery
