table FactStageEvent
	lineageTag: aaaaaaaa-0000-0000-0000-000000000038

	measure 'Leads Reaching Stage' = DISTINCTCOUNT('FactStageEvent'[LeadKey])
		formatString: 0
		lineageTag: aaaaaaaa-0000-0000-0000-000000000039

	column StageEventKey
		dataType: int64
		summarizeBy: none
		sourceColumn: StageEventKey
		lineageTag: aaaaaaaa-0000-0000-0000-000000000040

	column LeadKey
		dataType: int64
		summarizeBy: none
		sourceColumn: LeadKey
		lineageTag: aaaaaaaa-0000-0000-0000-000000000041

	column StageKey
		dataType: int64
		summarizeBy: none
		sourceColumn: StageKey
		lineageTag: aaaaaaaa-0000-0000-0000-000000000042

	column EnteredDateKey
		dataType: int64
		summarizeBy: none
		sourceColumn: EnteredDateKey
		lineageTag: aaaaaaaa-0000-0000-0000-000000000043

	partition FactStageEvent = entity
		mode: directLake
		source
			entityName: FactStageEvent
			schemaName: dbo
			expressionSource: DatabaseQuery
