SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE
FROM [lead-pipeline-app].INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME IN ('Reps', 'LeadSources', 'Leads', 'StageEvents')
ORDER BY TABLE_NAME, ORDINAL_POSITION;
